### ISSUE TITLE
Fails on High Sierra 

### ISSUE THREAD

**Issue by paynito** [jordonbiondo/osx-org-clock-menubar#3]

**Comment by paynito** [comment]
new install 
    
    chmod u+x /usr/local/bin/osm-server.rb
    macruby /usr/local/bin/osm-server.rb
    >>>>
    libmacruby.1.9.2.dylib' because Objective-C garbage collection is not supported

**Comment by jordonbiondo** [comment]
macruby has been deprecated for a while, the only fix is to rewrite the server in another language, probably obj-c or swift but honestly I'll probably never do that... I may just remove this project

**Comment by paynito** [comment]
No! just update the splash page README.org to say that it doesn't work and is orphaned, but here's the code if you want to rewrite it in Cocoa or whatever. (my 2¢)
